### PR TITLE
OpenGLQt: Use OpenGLWidget - rebase

### PR DESCRIPTION
**Pull request by ResearchDaniel**
Rebase of #951
Replaces deprecated use of QGLWidget.

### CODE REVIEW

**Comment by martinfalk** [comment]
There are two nasty warnings in qopenglcontext.h
See http://jenkins.inviwo.org:8080/job/inviwo/job/feature%252Fqt-openglwidget2/2/clang/


Details | File | Category | Severity | Age
-- | -- | -- | -- | --
  | qopenglcontext.h:55 | -W#warnings | Normal | 1
qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  | qopenglcontext.h:56 | -W#warnings | Normal | 1
To use GLEW with Qt, do not include or after glew.h

**Comment by ResearchDaniel** [comment]
> There are two nasty warnings in qopenglcontext.h
> See http://jenkins.inviwo.org:8080/job/inviwo/job/feature%252Fqt-openglwidget2/2/clang/
> 
> Details	File	Category	Severity	Age
>  	qopenglcontext.h:55	-W#warnings	Normal	1
> qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined				
>  	qopenglcontext.h:56	-W#warnings	Normal	1
> To use GLEW with Qt, do not include or after glew.h

Tried to fix it but I do not think it is possible without removing glew from the opengl module and using Qt's own function imports. Qt include this file internally...

**Comment by petersteneteg** [comment]
that should be easy to fix, why do you need to have all those includes in the header? you need to isolate them in the implementation.  If needed you can just add an extra layer to isolate them.

**Review by petersteneteg — DISMISSED** [review]

**Comment by ResearchDaniel** [comment]
@petersteneteg also removed compatibility profile now. There seem to be something wrong with doxygen preview image generation. Can you have a look?

**Comment by petersteneteg** [comment]
@ResearchDaniel 

`(lldb) run --save-previews .
Process 93466 launched: '/Users/jenkins/jenkins/workspace/inviwo_PR-958/build/bin/Inviwo.app/Contents/MacOS/Inviwo' (x86_64)
2020-06-18 17:09:16.292736+0200 Inviwo[93466:15982305] ApplePersistence=NO
2020-06-18 17:09:16.405117+0200 Inviwo[93466:15982363] MessageTracer: Falling back to default whitelist
2020-06-18 17:09:17.255974+0200 Inviwo[93466:15982305] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=93466
2020-06-18 17:09:17.256048+0200 Inviwo[93466:15982305] SecTaskCopyDebugDescription: Inviwo[93466]/0#-1 LF=0
2020-06-18 17:09:19.033606+0200 Inviwo Helper (GPU)[93471:15982444] MessageTracer: Falling back to default whitelist
2020-06-18 17:09:19.033671+0200 Inviwo Helper (GPU)[93471:15982444] MessageTracer: load_domain_whitelist_search_tree:85: Can't open default search tree file: Operation not permitted
2020-06-18 17:09:19.059194+0200 Inviwo Helper (GPU)[93471:15982435] GVA info: preferred scaler idx 1
2020-06-18 17:09:19.070011+0200 Inviwo Helper (GPU)[93471:15982444] MessageTracer: Falling back to default whitelist
2020-06-18 17:09:19.070135+0200 Inviwo Helper (GPU)[93471:15982444] MessageTracer: load_domain_whitelist_search_tree:85: Can't open default search tree file: Operation not permitted
Process 93466 stopped
* thread #1, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001012fdee2 libinviwo-module-webbrowser.dylib`inviwo::WebBrowserProcessor::WebBrowserProcessor(inviwo::InviwoApplication*) + 4018
libinviwo-module-webbrowser.dylib`inviwo::WebBrowserProcessor::WebBrowserProcessor:
->  0x1012fdee2 <+4018>: movq   (%rbx), %rax
    0x1012fdee5 <+4021>: leaq   -0x320(%rbp), %rdi
    0x1012fdeec <+4028>: movq   %rbx, %rsi
    0x1012fdeef <+4031>: movq   -0x648(%rbp), %r14
Target 0: (Inviwo) stopped.
(lldb) bt
* thread #1, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001012fdee2 libinviwo-module-webbrowser.dylib`inviwo::WebBrowserProcessor::WebBrowserProcessor(inviwo::InviwoApplication*) + 4018
    frame #1: 0x00000001013389f7 libinviwo-module-webbrowser.dylib`inviwo::ProcessorFactoryObjectTemplate<inviwo::WebBrowserProcessor>::create(inviwo::InviwoApplication*) + 55
    frame #2: 0x00000001080a5012 libinviwo-core.dylib`inviwo::ProcessorFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const + 50
    frame #3: 0x000000010018b94e libinviwo-qteditor.dylib`inviwo::utilqt::generatePreview(QString const&) + 302
    frame #4: 0x000000010018cd2e libinviwo-qteditor.dylib`inviwo::utilqt::saveProcessorPreviews(inviwo::InviwoApplication*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 750
    frame #5: 0x000000010829845f libinviwo-core.dylib`inviwo::CommandLineParser::processCallbacks() + 95
    frame #6: 0x0000000100012093 Inviwo`main + 1315
    frame #7: 0x00007fff583b53d5 libdyld.dylib`start + 1
(lldb) 
`

The web browser crashes when we start inviwo with --save-previews

**Comment by petersteneteg** [comment]
a debug build on mac gives OpenGL errors for all regressions... http://jenkins.inviwo.org:8080/job/inviwo/job/feature%252Fqt-openglwidget2/Regression/

**Comment by petersteneteg** [comment]
doxygen failure in debug
```
12:05:06  [14/15] Generate preview images of processors to be used in Inviwo Doxygen API documentation
12:05:06  FAILED: docs/CMakeFiles/DOXY-generate-processor-previews 
12:05:06  cd /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs && /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/bin/Inviwo.app/Contents/MacOS/Inviwo --save-previews /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs/inviwo/html --quit
12:05:06  2020-06-22 12:05:00.168 Inviwo[88386:18582996] ApplePersistence=NO
12:05:06  [0622/120504.415774:INFO:content_main_runner_impl.cc(960)] Chrome is running in full browser mode.
12:05:06  [0622/120505.729548:FATAL:cef_ref_counted.h(325)] Assert failed: ptr_ != __null.
12:05:06  /bin/sh: line 1: 88386 Trace/BPT trap: 5       /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/bin/Inviwo.app/Contents/MacOS/Inviwo --save-previews /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs/inviwo/html --quit
12:05:06  ninja: build stopped: subcommand failed.
```

**Comment by ResearchDaniel** [comment]
> doxygen failure in debug
> 
> ```
> 12:05:06  [14/15] Generate preview images of processors to be used in Inviwo Doxygen API documentation
> 12:05:06  FAILED: docs/CMakeFiles/DOXY-generate-processor-previews 
> 12:05:06  cd /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs && /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/bin/Inviwo.app/Contents/MacOS/Inviwo --save-previews /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs/inviwo/html --quit
> 12:05:06  2020-06-22 12:05:00.168 Inviwo[88386:18582996] ApplePersistence=NO
> 12:05:06  [0622/120504.415774:INFO:content_main_runner_impl.cc(960)] Chrome is running in full browser mode.
> 12:05:06  [0622/120505.729548:FATAL:cef_ref_counted.h(325)] Assert failed: ptr_ != __null.
> 12:05:06  /bin/sh: line 1: 88386 Trace/BPT trap: 5       /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/bin/Inviwo.app/Contents/MacOS/Inviwo --save-previews /Users/jenkins/jenkins/workspace/inviwo_feature_qt-openglwidget2/build/docs/inviwo/html --quit
> 12:05:06  ninja: build stopped: subcommand failed.
> ```

Hopefully fixed now

**Comment by petersteneteg** [comment]
You are still not supposed to merge master into a PR

**Comment by ResearchDaniel** [comment]
I just used the github web-ui for fixing the merge-conflicts 🤷‍♂️ Sigh

**Pull request closed without merging**
