### PR TITLE
Core: Interpolation refactoring

### PR DESCRIPTION
**Pull request by martinfalk**
* minor refactoring for better inlining

### CODE REVIEW

**Review by petersteneteg — APPROVED** [review]

**Review by ResearchDaniel — APPROVED** [review]
Looks good to me

**Comment by petersteneteg** [comment]
Humm why did we merge this? We have not solved the actual problem here, and this change might have broken other code

**Comment by ResearchDaniel** [comment]
It was approved and I needed the fixed to compile on my computer :)

**Comment by ResearchDaniel** [comment]
Ah, did not see that the other commit was after the approval

**Comment by ResearchDaniel** [comment]
Anyway, runs on Jenkins and fixes the problem so unless someone complains 🤷‍♂️

**Comment by petersteneteg** [comment]
Thats going to come back and bite us :(

**Pull request merged**
