### PR TITLE
CI: disabled doxygen for win builds, #1309

### PR DESCRIPTION
**Pull request by martinfalk**
Disable doxygen in CI workflow for windows builds due to #1309.

### CODE REVIEW

**Review by petersteneteg — CHANGES_REQUESTED** [review]
This output is used on the homepage. Should be fixed immediately not disabled

**Comment by martinfalk** [comment]
> This output is used on the homepage. Should be fixed immediately not disabled

I've looked into it for an entire day and was not able to figure out why `sphinx.ext.autosummary` does not accept the pyd files though the main sphinx loads the python modules. Excluding the autosummary "fixes" the build failing. But of course the generated docs are empty.

**Comment by petersteneteg** [comment]
Did you investigate what might have changed? This did work not that long ago?

**Comment by martinfalk** [comment]
Have not had time to track back the commits. Suspect it has to do with a commit regarding pydocs.

**Pull request closed without merging**
