### PR TITLE
Revert "Vcpkg: Linux fix?"

### PR DESCRIPTION
**Pull request by petersteneteg**
This reverts commit 668f8334e17fd660bf1221c2e48c7dc87d730977.

Fixes #...

Changes proposed in this PR:
 * ...
 * ...
 * ...

This has been tested on: ...

> Thank you for contributing to the Inviwo repository! Please ensure the following: 
> - Code is error and warning free
> - Code follows the Inviwo coding guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Coding-Conventions
> - New Code / Processors follows the Inviwo documentation guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Documentation-guide
> - New Code / processors are tested in a unittest and / or regression test: 
>   https://github.com/inviwo/inviwo/wiki/Manual#testing
> 
> Please remember to specify the environment this code been compiled and tested on:
> Operating System / Compiler / IDE / QT / CMake / Python versions.

### CODE REVIEW

**Review by ResearchDaniel — APPROVED** [review]
Nice fix! Should update the readme before merging

**Comment by petersteneteg** [comment]
Update the readme with what?

**Comment by ResearchDaniel** [comment]
> Update the readme with what?

That one must update vcpkg to the new commit

**Comment by petersteneteg** [comment]
Vcpkg will complain if you have a to old vcpkg repo. Same as every time we update the baseline, no different here. 
I really don't that to write any specific commits in the readme/manual etc, that will not age well. Maybe we should add some note that you should update you vcpkg repo when regularly.

**Comment by ResearchDaniel** [comment]
> Vcpkg will complain if you have a to old vcpkg repo. 

Ok, but the error message from vcpkg only indirectly says that the solution is to update the repo to commit X. 
It suggests that one should "updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure", which will not resolve the issue. 
Adding more detailed information about setting up vcpkg in the build instructions might be a good solution

**Pull request merged**
