### PR TITLE
clone inport data for transforms only when inport has changed.

### PR DESCRIPTION
**Pull request by VisComKreiser**
minimized data copy when properties change.

### CODE REVIEW

**Review by petersteneteg — CHANGES_REQUESTED** [review]
Hi
I understand why you want to do this, but in principle you are also not allowed to modify data that you have put once put in the inport. Imagine a processor later in the pipe line holding on to that data for background work etc. and then this processor goes and change it... Unfortunately the api we have do not enforce this. You can get around this by verifying that you are the only one holding on to the shared_ptr,... then changing it should be fine.

**Comment by petersteneteg** [comment]
I have also had designs where one might allow to make shallow clones of const volumes and meshes and so. and have copy on write functionality. But I have not had time to implement that.
And Im not sure if much API that would need to break for it to work...

**Comment by VisComKreiser** [comment]
Thanks for the elaborate answer, did not think about that case.
The issue we have is that we can not afford to copy huge volumes and several meshes in our application every frame when we transform things. Another alternative for us would be to incorporate a somewhat global transformation (similar to the transform processors) into the mesh renderer, volume raycaster and volume slice renderer, and attach it to the worldMatrix for rendering to be able to move stuff around all at the same time.
Maybe we can pick up that topic at the next meeting, the fance mesh renderer which is currently developed by the others also might benefit from some solution to this problem.

**Comment by petersteneteg** [comment]
Yes, we can have a discussion in the meeting. Think having a transform in the new rasterisers might be a good idea anyway

**Comment by AnkeAnke** [comment]
I'll add a transform matrix to the rasterizers (fancy mesh rendering etc). Also, since the output of the rasterizers, the rasteriation objects, are tiny, they can be easily copied to add a transform.

**Comment by VisComKreiser** [comment]
> I'll add a transform matrix to the rasterizers (fancy mesh rendering etc). Also, since the output of the rasterizers, the rasteriation objects, are tiny, they can be easily copied to add a transform.

Something similar to the Transform Processors would be nice to have.

**Comment by petersteneteg** [comment]
I'll close this now.

**Pull request closed without merging**
