### PR TITLE
BaseGL: Added min/max ranges to layout components of ImageLayoutGL

### PR DESCRIPTION
**Pull request by ResearchDaniel**
Now possible to restrict sizes of the layout components in ImageLayoutGL.

### CODE REVIEW

**Comment by ResearchDaniel** [comment]
Discovered one issue when making the window smaller than the specified min/max. Making the canvas larger again does not preserve the previously set min/max. Perhaps we could use the default values for this? E.g. setting the default if a resize event has smaller size and then restoring when/if the canvas gets bigger again.

Also, it would be nice if we could somehow prevent the canvas from getting smaller than the min size

**Comment by petersteneteg** [comment]
whats the reason for not just setting the min and max of the splitter?

**Comment by ResearchDaniel** [comment]
Those are given as percentages while the new min/max are in pixels. Setting splitter min/max will not give a fixed size

**Comment by petersteneteg** [comment]
This seems to me like you are adding a gui option in inviwo to configure a different gui. I think that configuration belong somewhere else.

**Comment by ResearchDaniel** [comment]
I think that it is rather standard layout options, e.g., https://www.w3schools.com/cssref/pr_dim_max-height.asp

**Comment by ResearchDaniel** [comment]
MinMaxSliders, however, might not be the best way to specify them

**Comment by ResearchDaniel** [comment]
Changed to text semantics and removed setting of max value. 
image

**Comment by ResearchDaniel** [comment]
@petersteneteg ping

**Review by petersteneteg — APPROVED** [review]

**Comment by ResearchDaniel** [comment]
Wait, I have some improvements coming up

**Comment by ResearchDaniel** [comment]
Now use our new isConnectionActive to deactivate zero-sized layout elements. Also added a grouping for min/max
image

**Pull request merged**
