### PR TITLE
Removes clang diagnostic warning

### PR DESCRIPTION
**Pull request by PetiteViking**
Warning: [clang-diagnostic-inconsistent-missing-destructor-override]

### CODE REVIEW

**Review by petersteneteg — APPROVED** [review]
Now you just have to add that to every overriding virtual destructor...

**Comment by JochenJankowai** [comment]
One at a time :)

**Comment by martinfalk** [comment]
Has this changed over time?

Found a discussion from 2016 where clang-tidy flagged the same thing and it was considered to be not correct.
https://github.com/isocpp/CppCoreGuidelines/issues/721

**Comment by petersteneteg** [comment]
Yes @martinfalk at the end of the discussion https://github.com/isocpp/CppCoreGuidelines/pull/1448

**Pull request merged**
