### PR TITLE
CMake: Fix in ivw_private_get_ivw_module_name for cmake incorrectly treating s as whitespace

### PR DESCRIPTION
**Pull request by r-englund**
See #580 

Seems cmake is treating a regular s in regexp mathcing as whitespace when using \\s for searching. changing \\s in to just a regular whitespace or putting the whitespace into brackets [ ] fixes the issue.

### CODE REVIEW

**Comment by r-englund** [comment]
Also, there is no need for checking for whitespace before or after the thing we looking for, cmake manage that anyway

**Comment by r-englund** [comment]
the use of `"[ \t\r\n]"` to find whitespaces is taken from https://cmake.org/cmake/help/latest/command/string.html 
> The quoted argument "[ \t\r\n]" specifies a regex that matches any single whitespace character.

**Review by petersteneteg — APPROVED** [review]

**Comment by r-englund** [comment]
@petersteneteg I added 1 commit after you approved. Now it checks the whole contents instead of line by line.  Still approved?
Now the regex would correctly parse this example: 
bild

**Comment by petersteneteg** [comment]
The only issue might be if one has two ivw_module and the first has a # in front... but we didn't fix that before either...

**Comment by petersteneteg** [comment]
In principle ivw_module should be at the beginning of the line except for space... but then one could put in inside a if or something so... it's still not fool proof...

**Comment by r-englund** [comment]
The check if it is in a comment and/or if-statement is too tricky to get into a single regex and would require some rework of the function so it out of scope for this PR, this at least fixes #580

**Pull request merged**
