### PR TITLE
ImageLayoutGL: Use proper error message in assertion

### PR DESCRIPTION
**Pull request by r-englund**

### CODE REVIEW

**Review by petersteneteg — APPROVED** [review]

**Review by ResearchDaniel — CHANGES_REQUESTED** [review]
The updated error text will not happen (or should not be necessary to check for at least). The assert will occur if someone decides to add another port and not adjust the code

**Comment by r-englund** [comment]
> The updated error text will not happen (or should not be necessary to check for at least). The assert will occur if someone decides to add another port and not adjust the code

and if that happens the error message should be descriptive

**Review by martinfalk — APPROVED** [review]

**Comment by martinfalk** [comment]
Have adjusted the error message.

**Comment by ResearchDaniel** [comment]
A lot of fuss for something that should not happen :) Adjusted the text slightly

**Review by ResearchDaniel — APPROVED** [review]

**Comment by petersteneteg** [comment]
Just so you know, the function is automatically added to the assert... https://github.com/inviwo/inviwo/blob/ac876d14cb18ee99e3604e3fce16e9456567f7d4/include/inviwo/core/util/assertion.h#L57

**Comment by r-englund** [comment]
> 
> 
> A lot of fuss for something that should not happen :) Adjusted the text slightly

And all started with me misunderstanding the test-expresion in the first place. Anyway, now we have a descriptive message.

**Pull request merged**
