### PR TITLE
Feature/dragspinbox

### PR DESCRIPTION
**Pull request by martinfalk**
New property semantics for ordinal properties: `SpinBox`

This widget allows to adjust the value by dragging the arrow up/down indicator with the mouse. The rate of change per sec is shown in a tooltip.

image

Other changes:
* refactoring of property widget registration in QtWidgets module
* minor fixes
* minor stylesheet adjustments (composites are now bold, child properties have same indentation as label)

### CODE REVIEW

**Comment by martinfalk** [comment]
## Comparison between `SpinBox` semantics and default sliders
image

**Review by ResearchDaniel — APPROVED** [review]
Ubernice

**Comment by petersteneteg** [comment]
Doh... forgot to reconnect Jenkins :(

**Review by petersteneteg — APPROVED** [review]
Can only agree with Daniel...

**Pull request merged**
