### PR TITLE
ModuleSystem: Fix CMake error when network editor is not enabled

### PR DESCRIPTION
**Pull request by ResearchDaniel**
Fixes CMake error when network editor is not enabled

This has been tested on: Windows

### CODE REVIEW

**Comment by petersteneteg** [comment]
Did you test if this still works for a regular build? I don't think the inviwo target exists when this is called, but since it uses generator expressions in the file generation it will look for inviwo at generation time when it does exist.

**Comment by petersteneteg** [comment]
I can refactor it if you want

**Comment by ResearchDaniel** [comment]
> Did you test if this still works for a regular build? I don't think the inviwo target exists when this is called, but since it uses generator expressions in the file generation it will look for inviwo at generation time when it does exist.

I did not. The runners should fail in that case I hope. More appropriate to have this code in the editor? Feel free to refactor.

**Comment by petersteneteg** [comment]
yes this broke regression http://jenkins.inviwo.org:8080/job/inviwo/job/PR-1492/

**Comment by ResearchDaniel** [comment]
Using IVW_APP_INVIWO instead of the target

**Review by petersteneteg — APPROVED** [review]

**Pull request merged**
