### PR TITLE
Assimp: Made AssimpReader look in both absolute and relative paths

### PR DESCRIPTION
**Pull request by ResearchDaniel**
Assimp: Made AssimpReader look in both absolute path and path relative to base path as done in many other readers.

### CODE REVIEW

**Review by r-englund — DISMISSED** [review]
Maybe this should, in this or another PR, become a utility function?

**Comment by ResearchDaniel** [comment]
@r-englund Hehe, had the same question to myself :)

**Comment by petersteneteg** [comment]
Why do we do this? seems really strange. Should only be relevant in the special case that we are referring to data shipped with inviwo? And should not be needed even then. 
If we want to consider a relative path, then that should be relative to the workspace file if any.
Also this should only be done on relative paths?

**Review by petersteneteg — CHANGES_REQUESTED** [review]
This seems like very questionable to be
is this documented behavior of our data readers?

**Comment by ResearchDaniel** [comment]
@petersteneteg Ah, perhaps it is done when saving the workspace instead. I did not check, just compared to the other readers. I will check and remove the code from the other readers as well in that case.

**Comment by ResearchDaniel** [comment]
FileProperty stores three paths in the workspace:
     1) Absolute
     2) Relative workspace
     3) Relative filesystem::getPath(PathType::Data)
FileProperty::deserialize looks for the file in the reverse order

Conclusion: Remove this kind of code in data readers

**Comment by ResearchDaniel** [comment]
Replaced by #78

**Pull request closed without merging**
