### PR TITLE
Base: DatVolumeSequenceReader fix for dat-file containing multiple fi…

### PR DESCRIPTION
**Pull request by ResearchDaniel**
…les. Each path in the file should be supplied relative to the containing dat-file, but the reader considered absolute path..

### CODE REVIEW

**Review by petersteneteg — CHANGES_REQUESTED** [review]
This is a breaking change is it not? Would it not be better to check if the given path is relative or not?

**Comment by ResearchDaniel** [comment]
The change to make it absolute was breaking, I'm restoring the original behaviour :)

**Comment by ResearchDaniel** [comment]
Also, using absolute paths would prevent one from moving any file

**Comment by petersteneteg** [comment]
Still it van break code

**Comment by petersteneteg** [comment]
In most other places we handle both

**Comment by ResearchDaniel** [comment]
The raw-files read below assumes the same thing. 
Other places handle absolute paths for the specific file, not for ones specified inside another, e.g. DICOM?

**Comment by ResearchDaniel** [comment]
@petersteneteg fixed, not it should handle both cases

**Review by petersteneteg — APPROVED** [review]

**Comment by ResearchDaniel** [comment]
@petersteneteg unrelated regression errors are the ones you fixed?

**Comment by petersteneteg** [comment]
@ResearchDaniel Yes so it seems

**Pull request merged**
