### PR TITLE
Base: removed c++17 dep...

### PR DESCRIPTION
**Pull request by petersteneteg**

### CODE REVIEW

**Comment by r-englund** [comment]
I can't spot where the change is

**Comment by r-englund** [comment]
> 
> 
> I can't spot where the change is

Found it. its the `std::is_same_v` -> `std::is_same<>::value`

**Review by r-englund — APPROVED** [review]
The only change I can see is `std::is_same_v` -> `std::is_same<>::value`. If thats it, then it is approved :)

**Comment by petersteneteg** [comment]
> The only change I can see is `std::is_same_v` -> `std::is_same<>::value`. If thats it, then it is approved :)

Yes, clang format did a big change... sorry about that

**Pull request merged**
