### PR TITLE
fix compile error on windows 10 with vs2019

### PR DESCRIPTION
**Pull request by maidamai0**
Fix compile error with:
* Windows 10
* Visual studio 2019 build tools
* Ninja

### CODE REVIEW

**Comment by maidamai0** [comment]
These two format error seems to be caused by old version `clang-format`. I formatted the code with the `clang-format` installed with `llvm-10.0`.

**Review by r-englund — APPROVED** [review]

**Comment by petersteneteg** [comment]
We try and use the same clangformat version that is shipping with visual studio. Think we use the one in vs2017 right now. Should probably update that to the one in vs2019. Unfortunately newer versions of clangformat does not format in the same way as older ones...

**Comment by maidamai0** [comment]
Jenkins uses clang-format 6.0 installed with llvm-6
``` shell
python3 ../inviwo/tools/jenkins/check-format.py --binary /usr/local/Cellar/llvm@6/6.0.1_1/bin/clang-format /Users/jenkins/jenkins/
clang-format version 6.0.1 (tags/RELEASE_601/final)
```

**Comment by petersteneteg** [comment]
Which I think is the same one that ships with msvc 2017

**Comment by petersteneteg** [comment]
see #1002

**Pull request merged**
