### PR TITLE
Property assignment

### PR DESCRIPTION
**Pull request by petersteneteg**
Removes operator= from Property and PropertyOwner. The sematics is strange, it is quite hard to get right, and we never use it.

### CODE REVIEW

**Review by ResearchDaniel — APPROVED** [review]
Should we perhaps say something about the owner not being transfered when cloning/copying and that the identifier must be changed after these two operations?

**Comment by petersteneteg** [comment]
@ResearchDaniel suggestions about where to say that? 
Property::clone?

**Comment by ResearchDaniel** [comment]
Yes, clone and copy constructor

**Comment by ResearchDaniel** [comment]
By the way, we should update the change log and say that people can just remove the = operator in their properties

**Review by martinfalk — APPROVED** [review]

**Pull request merged**
